---
title: "hw0"
author: ManglicmotRex
format: html
echo: false
---

```{r}
#define variables
a <- 1
b <- 3
c <- 2
```

Below is code the graph of the parabola as is.
```{r}
#plot the graph with variables
x <- seq(-5, 5, length = 300)
plot(x, a*x^2 + b*x + c, type = "l")
abline(h = 0, lty = 2)
```

```{r}
#I will now create the part of the code where there are 0, 1, or 2 solutions
#I will create part of the quadratic formula, sqrt(b^2 - 4*a*c), which will serve as a limiting factor

#sqrt of a positive number has solutions
#sqrt of zero has solutions
#sqrt of a negative number (not a real number) has no solutions 
quad <- sqrt(b^2 - 4*a*c) 
```

```{r}
#I will now create if and if-else statements to accommodate possible varying a, b, and c values 

#if and if-else statements for different values of quad
if (quad > 0) {
  #create separate parts of the quadratic formula that contains the plus and minus 
  #answers
  #two different numerical solutions will print out
  ans1 <- ((-b + quad) / (2*a))
  ans2 <- ((-b - quad) / (2*a))
  print(paste0("The roots of the parabola are: ", ans1, " and ", ans2))
  
} else if (quad == 0) {
  #create separate parts of the quadratic formula that contains the plus and minus 
  #answers
  #due to quad == 0, the positive and negative sign do not play a significant factor.
  #regardless, for code sake, I will write code
  #one same numerical solution will print out
  ans3 <- ((-b + quad) / (2*a))
  ans4 <- ((-b - quad) / (2*a))
  print(paste0("The root of the parabola are: ", ans3, " and ", ans4))
  
} else {
  #a negative sign cannot exist under a radial
  #no numerical solution will print out
  print(paste0("No solution"))
  
}
```